// Mocks generated by Mockito 5.4.0 from annotations
// in movie_unit_test/test/bloc/populer_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:http/io_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_unit_test/data/model/movie_model.dart' as _i5;
import 'package:movie_unit_test/data/services/api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIOClient_0 extends _i1.SmartFake implements _i2.IOClient {
  _FakeIOClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Api].
///
/// See the documentation for Mockito's code generation for more information.
class MockApi extends _i1.Mock implements _i3.Api {
  MockApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IOClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeIOClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.IOClient);
  @override
  _i4.Future<List<_i5.MovieModel>> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue: _i4.Future<List<_i5.MovieModel>>.value(<_i5.MovieModel>[]),
      ) as _i4.Future<List<_i5.MovieModel>>);
}
